CLASS zcl_00_handler DEFINITION PUBLIC
  FINAL CREATE PUBLIC
  FOR EVENTS OF Z00_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_00_HANDLER IMPLEMENTATION.
ENDCLASS.
