CLASS zcl_05_handler DEFINITION PUBLIC
  FINAL CREATE PUBLIC
  FOR EVENTS OF Z05_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_05_HANDLER IMPLEMENTATION.
ENDCLASS.
