CLASS zcl_07_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF Z07_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_07_handler IMPLEMENTATION.
ENDCLASS.
