CLASS zcl_02_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF Z02_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_02_handler IMPLEMENTATION.
ENDCLASS.
