CLASS zcl_08_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF Z08_R_Travel .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_08_handler IMPLEMENTATION.
ENDCLASS.
